# Load custom config
find ~/.dotfiles/zsh/config ~/.dotfiles/zsh/aliases -type f -name '*.zsh' -print0 | sort -z |
while IFS= read -r -d $'\0' line; do
	source "$line"
done

# Enable all completions
autoload -U compinit && compinit

# Load local config if present, for final overrides
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
