tap "homebrew/bundle"
tap "homebrew/cask-versions"

# Essentials
cask "raycast"
cask "google-chrome"
cask "visual-studio-code"

# Languages
brew "go"
brew "python"

# CLIs
brew "aws-elasticbeanstalk"
brew "awscli"
brew "docker"
brew "fnm"
brew "libpq"
brew "postgresql@14"
cask "dbeaver-community"
cask "docker"

# Apps & Utils
brew "ffmpeg"
brew "imagemagick"
cask "discord"
cask "firefox"
cask "imageoptim"
cask "microsoft-edge"
cask "numi"
cask "postman"
cask "qbittorrent"
cask "rectangle"
cask "slack"
cask "vlc"
cask "whatsapp"
cask "zoom"

# Games
cask "battle-net"
cask "epic-games"
cask "origin"
cask "steam"
cask "curseforge"
