#!/usr/bin/env bash

set -e
echo "Setup Homebrew starting..."
# Check if Homebrew is already installed
if ! command -v brew &> /dev/null; then
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # Eval Homebrew
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    echo "Homebrew is already installed."
fi

brew update
brew upgrade
brew bundle --file=./setup-homebrew/Brewfile
brew cleanup

echo "Setup Homebrew done!"
set +e